server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: myserver
spring:
  application.name:
    flat_service
  datasource:
    url: jdbc:postgresql://localhost:23455/studs
    username: s368601
    password: ${DB_PASSWORD:kIRfXLhf95PZkxZ6}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql:
      true
    properties:
      hibernate:
        generate_statistics:
          true
logging:
  level:
    root: info

agency:
  url: https://localhost:23223/agency/push