server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: myserver
spring:
  application.name:
    agency_service
  cassandra:
    keyspace-name: agencydb
    contact-points: localhost
    port: 23432
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
logging:
  level:
    root: info